// AUTO-GENERATED by tools/gen_profiles.py — DO NOT EDIT.
// Source of truth: config/profiles.yaml  /  Regenerate: python tools/gen_profiles.py
// schema_version=1
namespace PropKit
{
    public enum ProfileId { Fintokei=0, Ftmo=1, Normal=2 }
    public enum LossBasis { Equity = 0, Balance = 1 }
    public enum TotalBasis { InitialBalance = 0 }
    public enum NewsMode { Off = 0, Window = 1 }
    public enum BreachAction { Block = 0, FlattenHalt = 1 }

    public struct ProfileCfg
    {
        public string DisplayName;
        public double DailyLossPct;
        public LossBasis DailyLossBasis;
        public double TotalLossPct;
        public TotalBasis TotalLossBasis;
        public double MaxConcurrentRiskPct;
        public NewsMode NewsFilter;
        public int NewsWindowMin;
        public int MinHoldSeconds;
        public int MaxOpenPositions;
        public int MaxOrdersPerDay;
        public double MaxStrategyUsd;
        public BreachAction OnDailyBreach;
        public BreachAction OnTotalBreach;
        public double ProfitTargetPct;
    }

    public static class Profiles
    {
        public static readonly ProfileCfg[] All =
        {
            new ProfileCfg
            {
                DisplayName = "Fintokei (Challenge)",
                DailyLossPct = 5.0,
                DailyLossBasis = LossBasis.Equity,
                TotalLossPct = 10.0,
                TotalLossBasis = TotalBasis.InitialBalance,
                MaxConcurrentRiskPct = 3.0,
                NewsFilter = NewsMode.Off,
                NewsWindowMin = 0,
                MinHoldSeconds = 30,
                MaxOpenPositions = 0,
                MaxOrdersPerDay = 0,
                MaxStrategyUsd = 0.0,
                OnDailyBreach = BreachAction.Block,
                OnTotalBreach = BreachAction.FlattenHalt,
                ProfitTargetPct = 10.0,
            },
            new ProfileCfg
            {
                DisplayName = "FTMO (2-step Normal)",
                DailyLossPct = 5.0,
                DailyLossBasis = LossBasis.Balance,
                TotalLossPct = 10.0,
                TotalLossBasis = TotalBasis.InitialBalance,
                MaxConcurrentRiskPct = 0.0,
                NewsFilter = NewsMode.Window,
                NewsWindowMin = 2,
                MinHoldSeconds = 15,
                MaxOpenPositions = 200,
                MaxOrdersPerDay = 2000,
                MaxStrategyUsd = 400000.0,
                OnDailyBreach = BreachAction.Block,
                OnTotalBreach = BreachAction.FlattenHalt,
                ProfitTargetPct = 10.0,
            },
            new ProfileCfg
            {
                DisplayName = "Normal (live / unconstrained)",
                DailyLossPct = 0.0,
                DailyLossBasis = LossBasis.Balance,
                TotalLossPct = 0.0,
                TotalLossBasis = TotalBasis.InitialBalance,
                MaxConcurrentRiskPct = 0.0,
                NewsFilter = NewsMode.Off,
                NewsWindowMin = 0,
                MinHoldSeconds = 0,
                MaxOpenPositions = 0,
                MaxOrdersPerDay = 0,
                MaxStrategyUsd = 0.0,
                OnDailyBreach = BreachAction.Block,
                OnTotalBreach = BreachAction.Block,
                ProfitTargetPct = 0.0,
            },
        };

        public static ProfileCfg Get(ProfileId id) => All[(int)id];
    }
}
