#!/usr/bin/env python3
# =====================================================================
#  tools/gen_profiles.py
#  config/profiles.yaml（単一の真実の源）から各プラットフォームの
#  プロファイル定数ファイルを生成する。
#
#    framework/mql5/Profiles.mqh    (MQL5)
#    framework/mql4/Profiles.mqh    (MQL4 — MQL5 と同一構文)
#    framework/ctrader/Profiles.cs  (cTrader / C#)
#
#  使い方:
#    python tools/gen_profiles.py            # 生成（上書き）
#    python tools/gen_profiles.py --check    # 再生成して disk と diff。
#                                            # 古ければ非0終了（CI/pre-commit用）
#
#  ⚠ 生成ファイルは手で編集しない。YAML を直して再生成する。
# =====================================================================
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML が必要です:  pip install pyyaml  (requirements.txt にも追加済み)")

# Windows コンソール(cp932)でも壊れないよう標準出力を UTF-8 に。
try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

ROOT = Path(__file__).resolve().parent.parent
YAML_PATH = ROOT / "config" / "profiles.yaml"

OUT_MQL5 = ROOT / "framework" / "mql5" / "Profiles.mqh"
OUT_MQL4 = ROOT / "framework" / "mql4" / "Profiles.mqh"
OUT_CS = ROOT / "framework" / "ctrader" / "Profiles.cs"

# --- enum 値域（YAML の文字列 → 各言語の列挙子）-----------------------
LOSS_BASIS = {"equity": 0, "balance": 1}
TOTAL_BASIS = {"initial_balance": 0}
NEWS_MODE = {"off": 0, "window": 1}
BREACH = {"block": 0, "flatten_and_halt": 1}

# 列挙子名（MQL 側）
MQL_LOSS_BASIS = {"equity": "BASIS_EQUITY", "balance": "BASIS_BALANCE"}
MQL_TOTAL_BASIS = {"initial_balance": "TOTALBASIS_INITIAL_BALANCE"}
MQL_NEWS = {"off": "NEWS_OFF", "window": "NEWS_WINDOW"}
MQL_BREACH = {"block": "BREACH_BLOCK", "flatten_and_halt": "BREACH_FLATTEN_HALT"}

# 列挙子名（C# 側）
CS_LOSS_BASIS = {"equity": "LossBasis.Equity", "balance": "LossBasis.Balance"}
CS_TOTAL_BASIS = {"initial_balance": "TotalBasis.InitialBalance"}
CS_NEWS = {"off": "NewsMode.Off", "window": "NewsMode.Window"}
CS_BREACH = {"block": "BreachAction.Block", "flatten_and_halt": "BreachAction.FlattenHalt"}

REQUIRED_FIELDS = {
    "display_name": str,
    "daily_loss_pct": (int, float),
    "daily_loss_basis": str,
    "total_loss_pct": (int, float),
    "total_loss_basis": str,
    "max_concurrent_risk_pct": (int, float),
    "news_filter": str,
    "news_window_min": int,
    "min_hold_seconds": int,
    "max_open_positions": int,
    "max_orders_per_day": int,
    "max_strategy_usd": (int, float),
    "on_daily_breach": str,
    "on_total_breach": str,
    "profit_target_pct": (int, float),
}

HEADER_NOTE = (
    "AUTO-GENERATED by tools/gen_profiles.py — DO NOT EDIT.\n"
    "Source of truth: config/profiles.yaml  /  Regenerate: python tools/gen_profiles.py"
)


def load_and_validate() -> tuple[int, dict]:
    """YAML を読み、検証して (schema_version, profiles) を返す。"""
    if not YAML_PATH.exists():
        sys.exit(f"見つかりません: {YAML_PATH}")
    doc = yaml.safe_load(YAML_PATH.read_text(encoding="utf-8"))
    schema_version = int(doc.get("schema_version", 0))
    profiles = doc.get("profiles") or {}
    if not profiles:
        sys.exit("profiles が空です。")
    for name, cfg in profiles.items():
        if not name.isidentifier() or not name.isupper():
            sys.exit(f"プロファイル名は大文字の識別子にしてください: {name!r}")
        for field, typ in REQUIRED_FIELDS.items():
            if field not in cfg:
                sys.exit(f"[{name}] 必須フィールド欠落: {field}")
            if not isinstance(cfg[field], typ):
                sys.exit(f"[{name}] {field} の型不正: {cfg[field]!r}")
        _check_domain(name, "daily_loss_basis", cfg["daily_loss_basis"], LOSS_BASIS)
        _check_domain(name, "total_loss_basis", cfg["total_loss_basis"], TOTAL_BASIS)
        _check_domain(name, "news_filter", cfg["news_filter"], NEWS_MODE)
        _check_domain(name, "on_daily_breach", cfg["on_daily_breach"], BREACH)
        _check_domain(name, "on_total_breach", cfg["on_total_breach"], BREACH)
        for pct in ("daily_loss_pct", "total_loss_pct", "max_concurrent_risk_pct",
                    "profit_target_pct"):
            if not (0.0 <= float(cfg[pct]) <= 100.0):
                sys.exit(f"[{name}] {pct} は 0..100 の範囲: {cfg[pct]}")
    return schema_version, profiles


def _check_domain(name, field, value, domain):
    if value not in domain:
        sys.exit(f"[{name}] {field}={value!r} は許可外。許可値: {sorted(domain)}")


def cs_enum_member(profile_name: str) -> str:
    """FINTOKEI -> Fintokei, FTMO -> Ftmo, NORMAL -> Normal"""
    return profile_name[0].upper() + profile_name[1:].lower()


# ---------------------------------------------------------------------
#  MQL (MQL4 / MQL5 共通構文) ジェネレータ
# ---------------------------------------------------------------------
def gen_mql(schema_version: int, profiles: dict, dialect: str) -> str:
    names = list(profiles.keys())
    lines: list[str] = []
    a = lines.append
    a(f"//+------------------------------------------------------------------+")
    for ln in HEADER_NOTE.splitlines():
        a(f"//| {ln}")
    a(f"//| dialect={dialect}  schema_version={schema_version}")
    a(f"//+------------------------------------------------------------------+")
    a("#ifndef __PROPKIT_PROFILES_MQH__")
    a("#define __PROPKIT_PROFILES_MQH__")
    a("")
    # enums
    a("enum ENUM_PROFILE")
    a("  {")
    for i, n in enumerate(names):
        comma = "," if i < len(names) - 1 else ""
        a(f"   PROF_{n}={i}{comma}")
    a("  };")
    a("")
    a("enum ENUM_LOSS_BASIS { BASIS_EQUITY=0, BASIS_BALANCE=1 };")
    a("enum ENUM_TOTAL_BASIS { TOTALBASIS_INITIAL_BALANCE=0 };")
    a("enum ENUM_NEWS_MODE { NEWS_OFF=0, NEWS_WINDOW=1 };")
    a("enum ENUM_BREACH { BREACH_BLOCK=0, BREACH_FLATTEN_HALT=1 };")
    a("")
    # struct
    a("struct ProfileCfg")
    a("  {")
    a("   string          display_name;")
    a("   double          daily_loss_pct;")
    a("   ENUM_LOSS_BASIS daily_loss_basis;")
    a("   double          total_loss_pct;")
    a("   ENUM_TOTAL_BASIS total_loss_basis;")
    a("   double          max_concurrent_risk_pct;")
    a("   ENUM_NEWS_MODE  news_filter;")
    a("   int             news_window_min;")
    a("   int             min_hold_seconds;")
    a("   int             max_open_positions;")
    a("   int             max_orders_per_day;")
    a("   double          max_strategy_usd;")
    a("   ENUM_BREACH     on_daily_breach;")
    a("   ENUM_BREACH     on_total_breach;")
    a("   double          profit_target_pct;")
    a("  };")
    a("")
    a("//--- 全プロファイルを配列に充填（MQL は構造体配列リテラル不可のため関数で代入）")
    a(f"void ProfilesFill(ProfileCfg &a[])")
    a("  {")
    a(f"   ArrayResize(a,{len(names)});")
    for i, n in enumerate(names):
        c = profiles[n]
        a(f"   //--- {n}")
        a(f'   a[{i}].display_name           = "{c["display_name"]}";')
        a(f"   a[{i}].daily_loss_pct          = {float(c['daily_loss_pct'])};")
        a(f"   a[{i}].daily_loss_basis        = {MQL_LOSS_BASIS[c['daily_loss_basis']]};")
        a(f"   a[{i}].total_loss_pct          = {float(c['total_loss_pct'])};")
        a(f"   a[{i}].total_loss_basis        = {MQL_TOTAL_BASIS[c['total_loss_basis']]};")
        a(f"   a[{i}].max_concurrent_risk_pct = {float(c['max_concurrent_risk_pct'])};")
        a(f"   a[{i}].news_filter             = {MQL_NEWS[c['news_filter']]};")
        a(f"   a[{i}].news_window_min         = {int(c['news_window_min'])};")
        a(f"   a[{i}].min_hold_seconds        = {int(c['min_hold_seconds'])};")
        a(f"   a[{i}].max_open_positions      = {int(c['max_open_positions'])};")
        a(f"   a[{i}].max_orders_per_day      = {int(c['max_orders_per_day'])};")
        a(f"   a[{i}].max_strategy_usd        = {float(c['max_strategy_usd'])};")
        a(f"   a[{i}].on_daily_breach         = {MQL_BREACH[c['on_daily_breach']]};")
        a(f"   a[{i}].on_total_breach         = {MQL_BREACH[c['on_total_breach']]};")
        a(f"   a[{i}].profit_target_pct       = {float(c['profit_target_pct'])};")
    a("  }")
    a("")
    a("#endif // __PROPKIT_PROFILES_MQH__")
    a("")
    return "\n".join(lines)


# ---------------------------------------------------------------------
#  C# (cTrader) ジェネレータ
# ---------------------------------------------------------------------
def gen_cs(schema_version: int, profiles: dict) -> str:
    names = list(profiles.keys())
    lines: list[str] = []
    a = lines.append
    for ln in HEADER_NOTE.splitlines():
        a(f"// {ln}")
    a(f"// schema_version={schema_version}")
    a("namespace PropKit")
    a("{")
    # enums
    members = ", ".join(f"{cs_enum_member(n)}={i}" for i, n in enumerate(names))
    a(f"    public enum ProfileId {{ {members} }}")
    a("    public enum LossBasis { Equity = 0, Balance = 1 }")
    a("    public enum TotalBasis { InitialBalance = 0 }")
    a("    public enum NewsMode { Off = 0, Window = 1 }")
    a("    public enum BreachAction { Block = 0, FlattenHalt = 1 }")
    a("")
    # struct
    a("    public struct ProfileCfg")
    a("    {")
    a("        public string DisplayName;")
    a("        public double DailyLossPct;")
    a("        public LossBasis DailyLossBasis;")
    a("        public double TotalLossPct;")
    a("        public TotalBasis TotalLossBasis;")
    a("        public double MaxConcurrentRiskPct;")
    a("        public NewsMode NewsFilter;")
    a("        public int NewsWindowMin;")
    a("        public int MinHoldSeconds;")
    a("        public int MaxOpenPositions;")
    a("        public int MaxOrdersPerDay;")
    a("        public double MaxStrategyUsd;")
    a("        public BreachAction OnDailyBreach;")
    a("        public BreachAction OnTotalBreach;")
    a("        public double ProfitTargetPct;")
    a("    }")
    a("")
    a("    public static class Profiles")
    a("    {")
    a("        public static readonly ProfileCfg[] All =")
    a("        {")
    for n in names:
        c = profiles[n]
        a("            new ProfileCfg")
        a("            {")
        a(f'                DisplayName = "{c["display_name"]}",')
        a(f"                DailyLossPct = {float(c['daily_loss_pct'])},")
        a(f"                DailyLossBasis = {CS_LOSS_BASIS[c['daily_loss_basis']]},")
        a(f"                TotalLossPct = {float(c['total_loss_pct'])},")
        a(f"                TotalLossBasis = {CS_TOTAL_BASIS[c['total_loss_basis']]},")
        a(f"                MaxConcurrentRiskPct = {float(c['max_concurrent_risk_pct'])},")
        a(f"                NewsFilter = {CS_NEWS[c['news_filter']]},")
        a(f"                NewsWindowMin = {int(c['news_window_min'])},")
        a(f"                MinHoldSeconds = {int(c['min_hold_seconds'])},")
        a(f"                MaxOpenPositions = {int(c['max_open_positions'])},")
        a(f"                MaxOrdersPerDay = {int(c['max_orders_per_day'])},")
        a(f"                MaxStrategyUsd = {float(c['max_strategy_usd'])},")
        a(f"                OnDailyBreach = {CS_BREACH[c['on_daily_breach']]},")
        a(f"                OnTotalBreach = {CS_BREACH[c['on_total_breach']]},")
        a(f"                ProfitTargetPct = {float(c['profit_target_pct'])},")
        a("            },")
    a("        };")
    a("")
    a("        public static ProfileCfg Get(ProfileId id) => All[(int)id];")
    a("    }")
    a("}")
    a("")
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    """check=False: 書き込み。check=True: diff のみ。最新なら True。"""
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if check:
        if current == content:
            print(f"  OK   {path.relative_to(ROOT)}")
            return True
        print(f"  STALE {path.relative_to(ROOT)} (要 再生成)")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    if current == content:
        print(f"  unchanged {path.relative_to(ROOT)}")
    else:
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"  wrote     {path.relative_to(ROOT)}")
    return True


def main() -> int:
    ap = argparse.ArgumentParser(description="profiles.yaml から各言語の Profiles.* を生成")
    ap.add_argument("--check", action="store_true",
                    help="生成せず、disk が最新か検査（古ければ非0終了）")
    args = ap.parse_args()

    schema_version, profiles = load_and_validate()
    outputs = {
        OUT_MQL5: gen_mql(schema_version, profiles, "mql5"),
        OUT_MQL4: gen_mql(schema_version, profiles, "mql4"),
        OUT_CS: gen_cs(schema_version, profiles),
    }
    mode = "検査" if args.check else "生成"
    print(f"profiles.yaml → {len(profiles)} プロファイル / {mode}:")
    ok = True
    for path, content in outputs.items():
        ok = write_or_check(path, content, args.check) and ok
    if args.check and not ok:
        print("✗ 生成ファイルが古い。`python tools/gen_profiles.py` を実行して下さい。")
        return 1
    print("✓ 完了")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
