//+------------------------------------------------------------------+
//| AUTO-GENERATED by tools/gen_profiles.py — DO NOT EDIT.
//| Source of truth: config/profiles.yaml  /  Regenerate: python tools/gen_profiles.py
//| dialect=mql5  schema_version=1
//+------------------------------------------------------------------+
#ifndef __PROPKIT_PROFILES_MQH__
#define __PROPKIT_PROFILES_MQH__

enum ENUM_PROFILE
  {
   PROF_FINTOKEI=0,
   PROF_FTMO=1,
   PROF_NORMAL=2
  };

enum ENUM_LOSS_BASIS { BASIS_EQUITY=0, BASIS_BALANCE=1 };
enum ENUM_TOTAL_BASIS { TOTALBASIS_INITIAL_BALANCE=0 };
enum ENUM_NEWS_MODE { NEWS_OFF=0, NEWS_WINDOW=1 };
enum ENUM_BREACH { BREACH_BLOCK=0, BREACH_FLATTEN_HALT=1 };

struct ProfileCfg
  {
   string          display_name;
   double          daily_loss_pct;
   ENUM_LOSS_BASIS daily_loss_basis;
   double          total_loss_pct;
   ENUM_TOTAL_BASIS total_loss_basis;
   double          max_concurrent_risk_pct;
   ENUM_NEWS_MODE  news_filter;
   int             news_window_min;
   int             min_hold_seconds;
   int             max_open_positions;
   int             max_orders_per_day;
   double          max_strategy_usd;
   ENUM_BREACH     on_daily_breach;
   ENUM_BREACH     on_total_breach;
   double          profit_target_pct;
  };

//--- 全プロファイルを配列に充填（MQL は構造体配列リテラル不可のため関数で代入）
void ProfilesFill(ProfileCfg &a[])
  {
   ArrayResize(a,3);
   //--- FINTOKEI
   a[0].display_name           = "Fintokei (Challenge)";
   a[0].daily_loss_pct          = 5.0;
   a[0].daily_loss_basis        = BASIS_EQUITY;
   a[0].total_loss_pct          = 10.0;
   a[0].total_loss_basis        = TOTALBASIS_INITIAL_BALANCE;
   a[0].max_concurrent_risk_pct = 3.0;
   a[0].news_filter             = NEWS_OFF;
   a[0].news_window_min         = 0;
   a[0].min_hold_seconds        = 30;
   a[0].max_open_positions      = 0;
   a[0].max_orders_per_day      = 0;
   a[0].max_strategy_usd        = 0.0;
   a[0].on_daily_breach         = BREACH_BLOCK;
   a[0].on_total_breach         = BREACH_FLATTEN_HALT;
   a[0].profit_target_pct       = 10.0;
   //--- FTMO
   a[1].display_name           = "FTMO (2-step Normal)";
   a[1].daily_loss_pct          = 5.0;
   a[1].daily_loss_basis        = BASIS_BALANCE;
   a[1].total_loss_pct          = 10.0;
   a[1].total_loss_basis        = TOTALBASIS_INITIAL_BALANCE;
   a[1].max_concurrent_risk_pct = 0.0;
   a[1].news_filter             = NEWS_WINDOW;
   a[1].news_window_min         = 2;
   a[1].min_hold_seconds        = 15;
   a[1].max_open_positions      = 200;
   a[1].max_orders_per_day      = 2000;
   a[1].max_strategy_usd        = 400000.0;
   a[1].on_daily_breach         = BREACH_BLOCK;
   a[1].on_total_breach         = BREACH_FLATTEN_HALT;
   a[1].profit_target_pct       = 10.0;
   //--- NORMAL
   a[2].display_name           = "Normal (live / unconstrained)";
   a[2].daily_loss_pct          = 0.0;
   a[2].daily_loss_basis        = BASIS_BALANCE;
   a[2].total_loss_pct          = 0.0;
   a[2].total_loss_basis        = TOTALBASIS_INITIAL_BALANCE;
   a[2].max_concurrent_risk_pct = 0.0;
   a[2].news_filter             = NEWS_OFF;
   a[2].news_window_min         = 0;
   a[2].min_hold_seconds        = 0;
   a[2].max_open_positions      = 0;
   a[2].max_orders_per_day      = 0;
   a[2].max_strategy_usd        = 0.0;
   a[2].on_daily_breach         = BREACH_BLOCK;
   a[2].on_total_breach         = BREACH_BLOCK;
   a[2].profit_target_pct       = 0.0;
  }

#endif // __PROPKIT_PROFILES_MQH__
